---
- name: Configure ssh keys
  hosts: localhost
  tasks:
  - command: find /home/vagrant/sync/vagrant/.vagrant/machines -name private_key
    register: private_keys
    changed_when: no

  - file:
      src: "{{ item }}"
      dest: "/home/vagrant/.ssh/{{ item | regex_replace('^.*/machines/([^/]*)/.*', '\\1') }}.key"
      state: link
    with_items: "{{ private_keys.stdout_lines }}"


- name: Host bootstrapping
  hosts: all
  tasks:
  # Vagrant's "change host name" capability for Fedora/EL
  # maps hostname to loopback, conflicting with hostmanager.
  # We must repair /etc/hosts
  - lineinfile:
      path: /etc/hosts
      regexp: '^127\.0\.0\.1\s*\S*.{{ top_level_domain }}'
      state: absent
  - name: update /etc/hosts to resolve hostname to default IP address
    lineinfile:
      path: /etc/hosts
      insertafter: EOF
      line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
  - name: disable IPv6
    lineinfile:
      path: /etc/sysctl.conf
      regexp: "{{ item.regexp }}"
      insertafter: EOF
      line: "{{ item.line }}"
    with_items:
      - regexp: "^net.ipv6.conf.all.disable_ipv6"
        line: "net.ipv6.conf.all.disable_ipv6 = 1"
      - regexp: "^net.ipv6.conf.default.disable_ipv6"
        line: "net.ipv6.conf.default.disable_ipv6 = 1"
    register: disabled_ipv6
  - command: sysctl -p
    when: disabled_ipv6.changed

- name: Configure web servers
  hosts: web
  roles:
  - web
  - users
  - bash
